// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-reconciliation-sessions.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.8";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-reconciliation-sessions.ts
var list_reconciliation_sessions_default = defineTool({
  name: "list_reconciliation_sessions",
  title: "List reconciliation sessions",
  description: "List the signed-in user's reconciliation sessions (\u0627\u0644\u0641\u0631\u0632 \u0648\u0627\u0644\u0645\u0637\u0627\u0628\u0642\u0629), newest first, with status and branch.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of sessions to return."),
    status: z.string().trim().min(1).optional().describe("Optional status filter, e.g. draft, in_review, approved.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("reconciliation_sessions").select("id, name, branch, session_date, status, notes, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-reconciliation-session.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_reconciliation_session_default = defineTool2({
  name: "get_reconciliation_session",
  title: "Get reconciliation session",
  description: "Get one reconciliation session owned by the signed-in user, including its receipt pages, reference files and item match counts.",
  inputSchema: {
    session_id: z2.string().uuid().describe("The reconciliation session id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: session, error: sessionError } = await supabase.from("reconciliation_sessions").select("id, name, branch, session_date, status, notes, is_public, created_at, updated_at").eq("id", session_id).maybeSingle();
    if (sessionError) throw new ToolError2(sessionError.message);
    if (!session) throw new ToolError2("Session not found or not accessible");
    const [pages, references, items] = await Promise.all([
      supabase.from("receipt_pages").select("id, page_index, receipt_code, branch, receipt_date, review_status, extraction_status, extraction_error").eq("session_id", session_id).order("page_index", { ascending: true }),
      supabase.from("excel_snapshots").select("id, original_filename, file_kind, row_count, created_at").eq("session_id", session_id),
      supabase.from("receipt_items").select("match_status").eq("session_id", session_id)
    ]);
    for (const result of [pages, references, items]) {
      if (result.error) throw new ToolError2(result.error.message);
    }
    const counts = {};
    for (const item of items.data ?? []) {
      const key = item.match_status ?? "unmatched";
      counts[key] = (counts[key] ?? 0) + 1;
    }
    const payload = {
      session,
      pages: pages.data ?? [],
      reference_files: references.data ?? [],
      item_counts: counts,
      item_total: (items.data ?? []).length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-receipt-items.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_receipt_items_default = defineTool3({
  name: "list_receipt_items",
  title: "List receipt items",
  description: "List extracted receipt items for one reconciliation session, optionally filtered by match status (e.g. confirmed, partial, needs_review).",
  inputSchema: {
    session_id: z3.string().uuid().describe("The reconciliation session id."),
    match_status: z3.string().trim().min(1).optional().describe("Optional match status filter, e.g. confirmed, partial, needs_review."),
    limit: z3.number().int().min(1).max(200).default(50).describe("Maximum number of items to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, match_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("receipt_items").select(
      "id, item_index, item_code, description, corrected_description, unit, quantity, unit_price, total, match_status, match_score, reviewer_note"
    ).eq("session_id", session_id).order("item_index", { ascending: true }).limit(limit ?? 50);
    if (match_status) query = query.eq("match_status", match_status);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/review-receipt-item.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var review_receipt_item_default = defineTool4({
  name: "review_receipt_item",
  title: "Review receipt item",
  description: "Update the review outcome of one extracted receipt item: set its match status, a reviewer note, and/or a corrected description.",
  inputSchema: {
    item_id: z4.string().uuid().describe("The receipt item id."),
    match_status: z4.enum(["confirmed", "partial", "needs_review", "unmatched"]).nullable().describe("New match status, or null to leave unchanged."),
    reviewer_note: z4.string().trim().max(2e3).nullable().describe("Reviewer note to store, or null to leave unchanged."),
    corrected_description: z4.string().trim().max(2e3).nullable().describe("Corrected item description, or null to leave unchanged.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ item_id, match_status, reviewer_note, corrected_description }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const patch = {};
    if (match_status) patch.match_status = match_status;
    if (reviewer_note !== null) patch.reviewer_note = reviewer_note;
    if (corrected_description !== null) patch.corrected_description = corrected_description;
    if (Object.keys(patch).length === 0) throw new ToolError4("Nothing to update: provide at least one field");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("receipt_items").update(patch).eq("id", item_id).select("id, item_code, description, corrected_description, match_status, reviewer_note").maybeSingle();
    if (error) throw new ToolError4(error.message);
    if (!data) throw new ToolError4("Item not found or not accessible");
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/search-maintenance-items.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var search_maintenance_items_default = defineTool5({
  name: "search_maintenance_items",
  title: "Search maintenance items",
  description: "Search the maintenance reference dataset (\u0627\u0630\u0648\u0646\u0627\u062A \u0627\u0644\u0627\u0633\u062A\u0644\u0627\u0645) by item description, receipt code or branch. Requires an admin or moderator account.",
  inputSchema: {
    query: z5.string().trim().min(1).max(200).nullable().describe("Text to match in the item description, or null."),
    receipt_code: z5.string().trim().min(1).max(50).nullable().describe("Exact receipt code such as auf-001, or null."),
    limit: z5.number().int().min(1).max(200).default(50).describe("Maximum number of items to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, receipt_code, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("maintenance_items").select("id, receipt_code, item_index, item_date, branch, description, unit, quantity, unit_price, total, status").order("receipt_code", { ascending: true }).limit(limit ?? 50);
    if (receipt_code) request = request.eq("receipt_code", receipt_code);
    if (query) request = request.ilike("description", `%${query}%`);
    const { data, error } = await request;
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lyqkkrftypypnixaptms";
var mcp_default = defineMcp({
  name: "aztriage",
  title: "AzTriage",
  version: "0.1.0",
  instructions: "Tools for AzTriage maintenance receipt reconciliation (\u0627\u0644\u0641\u0631\u0632 \u0648\u0627\u0644\u0645\u0637\u0627\u0628\u0642\u0629). Use list_reconciliation_sessions to find sessions, get_reconciliation_session for a session's pages and match counts, list_receipt_items to inspect extracted items, review_receipt_item to record a review decision, and search_maintenance_items to look up the maintenance reference dataset.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_reconciliation_sessions_default,
    get_reconciliation_session_default,
    list_receipt_items_default,
    review_receipt_item_default,
    search_maintenance_items_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
