// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyqkkrftypypnixaptms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cWtrcmZ0eXB5cG5peGFwdG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NDQyMzEsImV4cCI6MjA5NTAyMDIzMX0.wq0KwqgClRvLdb70ezHNfTb7qrv1HsI7NYeY8BW1D0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});